# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fbcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'')),
                ('username', models.CharField(default=b'', max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fbpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=b'')),
                ('pagename', models.CharField(default=b'', max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ytcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'')),
                ('username', models.CharField(default=b'', max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('video', models.CharField(default=b'', max_length=100)),
                ('channel', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
